### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by eduarcor** [Freekers/docker-inviska#1]
Hello,
I am in Synology DSM 6.2.3 with docker. I have dozens of docker apps working already, so I have some experience with it.
I have a problem with the permissions.
I mapped properly the /media folder
After seeing that 0022 (default value) has the same problem I change UMASK to 0000, but with no luck.
![Screenshot 2024-02-12 at 16 27 49](https://github.com/Freekers/docker-inviska/assets/1464379/c5da4646-3a2b-4ea7-96d4-a82d885ec74e)
Hope you could help me. Thanks

EDIT: Issue was USERID/GROUPID, once is populated correctly it works.

**Comment by Freekers** [comment]
@eduarcor Glad to hear it worked out in the end. Thanks for sharing the solution in case others face the same issue.
